### ISSUE TITLE
random crash doing undo -- something out of whack

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/cogent#270]
panic: runtime error: slice bounds out of range [98:88]

goroutine 15 [running]:
github.com/goki/gi/giv.(*TextBuf).DeleteTextImpl(0xc0d2802580, 0xf2, 0x5e, 0xf2, 0x62, 0xc06182ba70)
        /Users/oreilly/go/src/github.com/goki/gi/giv/textbuf.go:1081 +0x778
github.com/goki/gi/giv.(*TextBuf).Undo(0xc0d2802580, 0x0)
        /Users/oreilly/go/src/github.com/goki/gi/giv/textbuf.go:1873 +0x6b3
github.com/goki/gi/giv.(*TextView).Undo(0xc004bc4a00)
        /Users/oreilly/go/src/github.com/goki/gi/giv/textview.go:1536 +0x7c
github.com/goki/gi/giv.(*TextView).KeyInput(0xc004bc4a00, 0xc11a47bc80)
        /Users/oreilly/go/src/github.com/goki/gi/giv/textview.go:4279 +0x1059
github.com/goki/gide/gide.(*TextView).TextViewEvents.func2(0x520d5e0, 0xc004bc4a00, 0x51f7320, 0xc000825000, 0x7, 0x4ea3d80, 0xc11a47bc80)
        /Users/oreilly/go/src/github.com/goki/gide/gide/textview.go:269 +0x8c
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc06182bdb8, 0x51f7320, 0xc000825000, 0x7, 0x4ea3d80, 0xc11a47bc80)
        /Users/oreilly/go/src/github.com/goki/gi/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc000825198, 0x51ab0e0, 0xc11a47bc80, 0x1)
        /Users/oreilly/go/src/github.com/goki/gi/gi/events.go:225 +0x39b
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc000825000, 0x51ab0e0, 0xc11a47bc80)
        /Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1547 +0x845
github.com/goki/gi/gi.(*Window).EventLoop(0xc000825000)
        /Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1469 +0x36
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
        /Users/oreilly/go/src/github.com/goki/gi/gi/window.go:876 +0xa7

**Comment by rcoreilly** [comment]
similar -- just needs some basic bounds checking

panic: runtime error: slice bounds out of range [1:0]

goroutine 276 [running]:
github.com/goki/gi/giv.(*TextBuf).DeleteTextImpl(0xc0064bf900, 0x1ac, 0x0, 0x1ac, 0x1, 0xc03c37ba70)
        /Users/oreilly/go/src/github.com/goki/gi/giv/textbuf.go:1082 +0x778
github.com/goki/gi/giv.(*TextBuf).Undo(0xc0064bf900, 0x0)
        /Users/oreilly/go/src/github.com/goki/gi/giv/textbuf.go:1874 +0x6b3
github.com/goki/gi/giv.(*TextView).Undo(0xc004285500)
        /Users/oreilly/go/src/github.com/goki/gi/giv/textview.go:1538 +0x7c
github.com/goki/gi/giv.(*TextView).KeyInput(0xc004285500, 0xc02f6cea80)
        /Users/oreilly/go/src/github.com/goki/gi/giv/textview.go:4281 +0x1059
github.com/goki/gide/gide.(*TextView).TextViewEvents.func2(0x520f640, 0xc004285500, 0x51f9380, 0xc000f1a000, 0x7, 0x4eab3a0, 0xc02f6cea80)
        /Users/oreilly/go/src/github.com/goki/gide/gide/textview.go:270 +0x8c
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc03c37bdb8, 0x51f9380, 0xc000f1a000, 0x7, 0x4eab3a0, 0xc02f6cea80)
        /Users/oreilly/go/src/github.com/goki/gi/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc000f1a198, 0x51afbc0, 0xc02f6cea80, 0x1)
        /Users/oreilly/go/src/github.com/goki/gi/gi/events.go:225 +0x39b
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc000f1a000, 0x51afbc0, 0xc02f6cea80)
        /Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1547 +0x853
github.com/goki/gi/gi.(*Window).EventLoop(0xc000f1a000)
        /Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1469 +0x36
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
        /Users/oreilly/go/src/github.com/goki/gi/gi/window.go:876 +0xa7

**Comment by rcoreilly** [comment]
added some checks in RegionImpl -- may not be full fix

**Comment by rcoreilly** [comment]
out of date
